skillfair/config/routes.rb
Rails.application.routes.draw do
  resources :products
  root "products#index"
end

skillfair/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

skillfair/app/models/product.rb
class Product < ApplicationRecord
end

skillfair/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

skillfair/app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: %i[ show edit update destroy ]

  # GET /products or /products.json
  def index
    @products = Product.all
  end

  # GET /products/1 or /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products or /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: "Product was successfully created." }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1 or /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: "Product was successfully updated." }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1 or /products/1.json
  def destroy
    @product.destroy!

    respond_to do |format|
      format.html { redirect_to products_path, status: :see_other, notice: "Product was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def product_params
      params.expect(product: [ :label, :image_url ])
    end
end

skillfair/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

skillfair/app/helpers/application_helper.rb
module ApplicationHelper
end

skillfair/app/helpers/products_helper.rb
module ProductsHelper
end

skillfair/app/helpers/welcome_helper.rb
module WelcomeHelper
end

skillfair/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Skillfair" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>


<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css"/>

  <link href='https://fonts.googleapis.com/css?family=Roboto:300,400,700' rel='stylesheet' type='text/css'>


  <body>
    <%= yield %>
  </body>
</html>

skillfair/app/views/products/_form.html.erb
<%= form_with(model: product) do |form| %>
  <% if product.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
        <% product.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :label, style: "display: block" %>
    <%= form.text_field :label %>
  </div>

  <div>
    <%= form.label :image_url, style: "display: block" %>
    <%= form.text_field :image_url %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

skillfair/app/views/products/_product.html.erb
<div id="<%= dom_id product %>">
  <p>
    <strong>Label:</strong>
    <%= product.label %>
  </p>

  <p>
    <strong>Image url:</strong>
    <%= product.image_url %>
  </p>

</div>

skillfair/app/views/products/edit.html.erb
<% content_for :title, "Editing product" %>

<h1>Editing product</h1>

<%= render "form", product: @product %>

<br>

<div>
  <%= link_to "Show this product", @product %> |
  <%= link_to "Back to products", products_path %>
</div>

skillfair/app/views/products/index.html.erb
<p style="color: green"><%= notice %></p>


<header class="container">
    <div class="row">
      <h1 class="col-sm-8">Skillfair</h1>
      <nav class="col-sm-4">
        <p>newest</p>
        <p>catalogue</p>
        <p>contact</p>
      </nav>
    </div>
  </header>
  <section class="jumbotron">
    <div class="container">
      <div class="row text-center">
        <h2>Homemade Goods</h2>
        <h3>This Year's Best</h3>
        <a class="btn btn-primary" href="#">See all</a>
      </div>
    </div>
  </section>




<%= link_to "Products", products_path %>


<h1>Homemade Goods</h1>
<h3>This Year's Best</h3>
<a class="btn btn-primary" href="#">See all</a>

<section class="container mt-4">
  <div class="row">
    <% @products.each do |product| %>
      <div class="col-sm-6">
        <p><%= product.label %></p>
        <img src="<%= product.image_url %>" class="img-fluid">
      </div>
    <% end %>
  </div>
  <div class="row text-center mt-3">
    <a class="btn btn-secondary" href="#">View Complete Catalogue</a>
  </div>
</section>


<footer class="container">
    <div class="row">
      <p class="col-sm-4">&copy; 2016 Skillfair</p>
      <ul class="col-sm-8">
        <li class="col-sm-1">
          <img src="https://content.codecademy.com/projects/make-a-website/lesson-4/twitter.svg">
        </li>
        <li class="col-sm-1">
          <img src="https://content.codecademy.com/projects/make-a-website/lesson-4/facebook.svg">
        </li>
        <li class="col-sm-1">
          <img src="https://content.codecademy.com/projects/make-a-website/lesson-4/instagram.svg">
        </li>
        <li class="col-sm-1">
          <img src="https://content.codecademy.com/projects/make-a-website/lesson-4/medium.svg">
        </li>
      </ul>
    </div>
  </footer>


<%= link_to "Products", products_path %>

skillfair/app/views/products/new.html.erb
<% content_for :title, "New product" %>

<h1>New product</h1>

<%= render "form", product: @product %>

<br>

<div>
  <%= link_to "Back to products", products_path %>
</div>

skillfair/app/views/products/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @product %>

<div>
  <%= link_to "Edit this product", edit_product_path(@product) %> |
  <%= link_to "Back to products", products_path %>

  <%= button_to "Destroy this product", @product, method: :delete %>
</div>

skillfair/app/views/welcome/index.html.erb
<header class="container">
    <div class="row">
      <h1 class="col-sm-8">Skillfair</h1>
      <nav class="col-sm-4">
        <p>newest</p>
        <p>catalogue</p>
        <p>contact</p>
      </nav>
    </div>
  </header>
  <section class="jumbotron">
    <div class="container">
      <div class="row text-center">
        <h2>Homemade Goods</h2>
        <h3>This Year's Best</h3>
        <a class="btn btn-primary" href="#">See all</a>
      </div>
    </div>
  </section>
  <section class="container">
    <div class="row">
      <div class="col-sm-6">
        <p>kitchen</p>
        <img src="https://content.codecademy.com/projects/make-a-website/lesson-4/kitchen.jpg">
      </div>
      <div class="col-sm-6">
        <p>woodwork</p>
        <img src="https://content.codecademy.com/projects/make-a-website/lesson-4/woodwork.jpg">
      </div>
      <div class="col-sm-6">
        <p>gifts</p>
        <img src="https://content.codecademy.com/projects/make-a-website/lesson-4/gifts.jpg">
      </div>
      <div class="col-sm-6">
        <p>antiques</p>
        <img src="https://content.codecademy.com/projects/make-a-website/lesson-4/antique.jpg">
      </div>
    </div>
    <div class="row text-center">
      <a class="btn btn-secondary" href="#">View Complete Catalogue</a>
    </div>
  </section>
  <footer class="container">
    <div class="row">
      <p class="col-sm-4">&copy; 2016 Skillfair</p>
      <ul class="col-sm-8">
        <li class="col-sm-1">
          <img src="https://content.codecademy.com/projects/make-a-website/lesson-4/twitter.svg">
        </li>
        <li class="col-sm-1">
          <img src="https://content.codecademy.com/projects/make-a-website/lesson-4/facebook.svg">
        </li>
        <li class="col-sm-1">
          <img src="https://content.codecademy.com/projects/make-a-website/lesson-4/instagram.svg">
        </li>
        <li class="col-sm-1">
          <img src="https://content.codecademy.com/projects/make-a-website/lesson-4/medium.svg">
        </li>
      </ul>
    </div>
  </footer>